# Generated by Django 4.0.4 on 2022-05-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('strain', models.CharField(max_length=254)),
                ('image', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.IntegerField(default=100)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.colourmodel')),
            ],
        ),
    ]
